CREATE TABLE IF NOT EXISTS schema_migrations (
  version INTEGER PRIMARY KEY,
  applied_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS services (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  config JSONB NOT NULL
);
CREATE TABLE IF NOT EXISTS workers (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  idclient TEXT NOT NULL,
  "user" TEXT NOT NULL,
  secret TEXT NOT NULL,
  active BOOLEAN NOT NULL DEFAULT false,
  "serviceId" INTEGER NOT NULL REFERENCES services(id),
  status TEXT NOT NULL DEFAULT 'idle' CHECK (status IN ('idle','running','error')),
  "nextRun" BIGINT NOT NULL DEFAULT 0,
  "lastRun" BIGINT,
  "lastSuccess" BIGINT,
  failures INTEGER NOT NULL DEFAULT 0,
  error TEXT,
  mark TEXT NOT NULL DEFAULT ''
);
CREATE TABLE IF NOT EXISTS runs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "workerId" INTEGER NOT NULL REFERENCES workers(id) ON DELETE CASCADE,
  started BIGINT NOT NULL,
  finished BIGINT NOT NULL,
  success BOOLEAN NOT NULL,
  error TEXT,
  payload JSONB,
  "rawXml" TEXT
);
CREATE INDEX IF NOT EXISTS runs_worker ON runs("workerId",id DESC);
CREATE INDEX IF NOT EXISTS workers_due ON workers("nextRun",id) WHERE active AND status <> 'running';
CREATE INDEX IF NOT EXISTS workers_service ON workers("serviceId");
CREATE TABLE IF NOT EXISTS settings (key TEXT PRIMARY KEY,value TEXT NOT NULL);
INSERT INTO settings VALUES ('enabled','true') ON CONFLICT DO NOTHING;
INSERT INTO schema_migrations(version) VALUES (1) ON CONFLICT DO NOTHING;
